In [1]:
import numpy as np

In [2]:
saran = [19,'saran','chennai',9988776655]
type(saran)

list

Data Structure conversion

In [3]:
saran_arr = np.array(saran)

In [4]:
s = saran.copy

In [6]:
s = (19,'saran','chennai',9988776655)
type(s)

tuple

In [7]:
s_arr = np.array(s)
type(s_arr)

numpy.ndarray

In [10]:
dict = {2:3,4:6,5:7}
type(dict)

dict

In [11]:
dict_arr = np.array(dict)
type(dict_arr)

numpy.ndarray

In [12]:
sr = {2,3,4,5,6,7,8,9}
type(sr)

set

In [13]:
sr_arr = np.array(sr)
type(sr_arr)

numpy.ndarray

In [17]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

In [18]:
a_arr = np.array(a)
b_arr = np.array(b)

In [32]:
 v = a_arr + b_arr
 v         # addition of array

array([ 7,  9, 11, 13, 15])

In [23]:
c = np.concatenate([a_arr,b_arr])            # array should be passed in the list
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
cc = np.append(a_arr,b_arr)
cc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# view creation of array
d = np.vstack([a_arr,b_arr])
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
d = np.vstack([a_arr])                # normal view / direct view
d

array([[1, 2, 3, 4, 5]])

In [28]:
e = np.hstack([a_arr,b_arr])
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
t = np.transpose([a_arr,b_arr])
t

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [33]:
s = np.array([[2,4,6],[3,5,7],[7,8,9]])
s.ndim

2

In [34]:
s.shape

(3, 3)

In [35]:
s.reshape(9,1)

array([[2],
       [4],
       [6],
       [3],
       [5],
       [7],
       [7],
       [8],
       [9]])

In [36]:
# array broadcasting
s.min()

2

In [37]:
s.max()

9

In [38]:
s.sum()

51

In [39]:
s.mean()

5.666666666666667

In [44]:
s.mode()

AttributeError: ignored

In [45]:
s.median()

AttributeError: ignored

In [42]:
x = [1,2,3,4,5]
type(x)

list

In [46]:
s.cumsum()                # cumulative frequency

array([ 2,  6, 12, 15, 20, 27, 34, 42, 51])

In [48]:
arr_s = np.arange(1,100,2)                       # last value is step value
arr_s

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [49]:
print(arr_s[arr_s>60])

[61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


Dimensionality change

In [51]:
arr_s.flatten()


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [52]:
arr_s.ravel()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Creating  various kinds of array

In [53]:
arr_s = np.empty((5,3))
arr_s

array([[4.85589432e-310, 0.00000000e+000, 1.33856858e-152],
       [3.86585424e+233, 2.46343043e-154, 9.74726073e+024],
       [2.32160957e-152, 4.26252834e+257, 6.98114906e+194],
       [8.71280277e+183, 1.10101759e+155, 3.11078391e+161],
       [4.95890384e+173, 7.52591416e+199, 1.02765654e-321]])

In [82]:
a = []
type(a)

list

In [83]:
b = np.array(a)
b

array([], dtype=float64)

In [62]:
g = np.empty((b))
g

array(1.03e-321)

In [63]:
g = np.empty([])
g

array(1.03e-321)

In [64]:
np.zeros((2,5,4))     # number of array , rows , columns

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
np.ones(4)                        # default in floating

array([1., 1., 1., 1.])

In [66]:
np.ones((4),dtype=int)

array([1, 1, 1, 1])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.linspace((10,2),3)

array([[10.        ,  2.        ],
       [ 9.85714286,  2.02040816],
       [ 9.71428571,  2.04081633],
       [ 9.57142857,  2.06122449],
       [ 9.42857143,  2.08163265],
       [ 9.28571429,  2.10204082],
       [ 9.14285714,  2.12244898],
       [ 9.        ,  2.14285714],
       [ 8.85714286,  2.16326531],
       [ 8.71428571,  2.18367347],
       [ 8.57142857,  2.20408163],
       [ 8.42857143,  2.2244898 ],
       [ 8.28571429,  2.24489796],
       [ 8.14285714,  2.26530612],
       [ 8.        ,  2.28571429],
       [ 7.85714286,  2.30612245],
       [ 7.71428571,  2.32653061],
       [ 7.57142857,  2.34693878],
       [ 7.42857143,  2.36734694],
       [ 7.28571429,  2.3877551 ],
       [ 7.14285714,  2.40816327],
       [ 7.        ,  2.42857143],
       [ 6.85714286,  2.44897959],
       [ 6.71428571,  2.46938776],
       [ 6.57142857,  2.48979592],
       [ 6.42857143,  2.51020408],
       [ 6.28571429,  2.53061224],
       [ 6.14285714,  2.55102041],
       [ 6.        ,

In [73]:
np.linspace(0,2,90)

array([0.        , 0.02247191, 0.04494382, 0.06741573, 0.08988764,
       0.11235955, 0.13483146, 0.15730337, 0.17977528, 0.20224719,
       0.2247191 , 0.24719101, 0.26966292, 0.29213483, 0.31460674,
       0.33707865, 0.35955056, 0.38202247, 0.40449438, 0.42696629,
       0.4494382 , 0.47191011, 0.49438202, 0.51685393, 0.53932584,
       0.56179775, 0.58426966, 0.60674157, 0.62921348, 0.65168539,
       0.6741573 , 0.69662921, 0.71910112, 0.74157303, 0.76404494,
       0.78651685, 0.80898876, 0.83146067, 0.85393258, 0.87640449,
       0.8988764 , 0.92134831, 0.94382022, 0.96629213, 0.98876404,
       1.01123596, 1.03370787, 1.05617978, 1.07865169, 1.1011236 ,
       1.12359551, 1.14606742, 1.16853933, 1.19101124, 1.21348315,
       1.23595506, 1.25842697, 1.28089888, 1.30337079, 1.3258427 ,
       1.34831461, 1.37078652, 1.39325843, 1.41573034, 1.43820225,
       1.46067416, 1.48314607, 1.50561798, 1.52808989, 1.5505618 ,
       1.57303371, 1.59550562, 1.61797753, 1.64044944, 1.66292

Array Indexing

In [74]:
t = np.array([[5,3,9,10],[6,7,8,3],[7,5,7,9]])        # matrix
t

array([[ 5,  3,  9, 10],
       [ 6,  7,  8,  3],
       [ 7,  5,  7,  9]])

In [75]:
t[0:1]

array([[ 5,  3,  9, 10]])

In [76]:
t[0]

array([ 5,  3,  9, 10])

In [77]:
t[0,1]

3

In [78]:
t[0:2,1]

array([3, 7])

In [79]:
t[1:3,2:4]

array([[8, 3],
       [7, 9]])

In [80]:
t % 2 == 0

array([[False, False, False,  True],
       [ True, False,  True, False],
       [False, False, False, False]])

In [81]:
t[t % 2 == 0]     # show the value whever the condition is true

array([10,  6,  8])